drop database if exists san;
create database if not exists san;
use san;
create table usuario(
id bigint not null unique auto_increment primary key,
nome varchar(70) not null,
email varchar(70) not null,
senha varchar(70) not null,
isNutr int default 1
);
-- TRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERS
-- TRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERS
-- 
--                                    Triggers da tabela mvcx_e
-- 
-- TRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERS
-- TRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERSTRIGGERS
delimiter ;
drop trigger if exists aplicarMD5;
delimiter $$
create trigger aplicarMD5
before insert on usuario for each row
begin
	set new.senha := md5(new.senha);
end;$$
delimiter ;
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
--
--                                    Popular banco
--
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
-- POPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCOPOPULARBANCO
--
--
-- Inserindo usuários cliente de nutricionistas
insert into usuario (nome, email, senha, isNutr) values ('tulio','tulio@email','tulio',0);
insert into usuario (nome, email, senha, isNutr) values ('joao','joao@email','joao',0);
insert into usuario (nome, email, senha, isNutr) values ('augusto','augusto@email','augusto',0);
insert into usuario (nome, email, senha, isNutr) values ('danilo','danilo@email','danilo',0);
